name: "Mirror"

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 20 * * *'

jobs:
  run:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Manually mirror
      run: |
        mirror() {
          git clone "https://github.com/$1/$2"
          cd "$2"
          git remote add gitee "https://dyrnq:${{ secrets.GITEE_TOKEN }}@gitee.com/dyrnq/$2.git"
          git remote set-head origin -d
          git push gitee --prune +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
          cd ..
        }
        mirror dyrnq centos7-docker-flanneld-consul-example
        #mirror dyrnq linux-command
        #mirror dyrnq hotkeys
        #mirror dyrnq oscnews
        #mirror dyrnq iNotify
        #mirror dyrnq sgo
        #mirror dyrnq oscnews
        #mirror dyrnq mocker-api
        #mirror dyrnq vim-web
        #mirror dyrnq translater.js
